[respondd]
enable           = true
interface        = "eth0"
collect_interval = "1m"


[webserver]
enable  = false
bind    = "127.0.0.1:8080"
webroot = "webroot"


[nodes]
enable         = true
nodes_version  = 2
nodes_path     = "/var/www/html/meshviewer/data/nodes.json"
graph_path     = "/var/www/html/meshviewer/data/graph.json"
state_path     = "/var/lib/collector/state.json"

# Export nodes and graph periodically
save_interval = "5s"

# Set node to offline if not seen within this period
offline_after = "10m"

# Prune offline nodes after a time of inactivity
prune_after = "7d"


[influxdb]
enable   = false
address  = "http://localhost:8086"
database = "ffhb"
username = ""
password = ""
